### ISSUE TITLE
Filesystem hangs when trying to modify files after parallel copy

### ISSUE THREAD

**Issue by d-uzlov** [openzfsonwindows/openzfs#247]
### System information

```powershell
PS C:\Windows\system32> zfs version
zfswin-2.2.0rc1
zfs-kmod-zfswin-2.2.0rc1

PS C:\Windows\system32> [System.Environment]::OSVersion

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19045.0 Microsoft Windows NT 10.0.19045.0
```

### Describe the problem you're observing

I tried to copy files from a remote network drive to a local one with ZFS.

I used `robocopy` with 32 threads, maybe multithreading affected this (I didn't have such issues before I used parallel copy).

```powershell
robocopy n:\archive\Backup\a\Programs L:\Programs /E /MT:32 /E
```

At some point the copy process stalled, and robocopy hanged, I couldn't even stop it.
I tried to repeat it, but now it stalled immediately.
I tried to run to compare files to check how many files were actually copied, but the comparison also hanged, and I couldn't close the program.
I tried to remove the copied files but the "Delete" operation also hangs, and I can't even cancel it.

I checked a few files, and it seems like I can at least read them (though, maybe it's only because of ARC, I didn't check too thoroughly, and diff comparison also hanged, despite it doesn't write anything).

15 minutes passed and nothing happened.
Right now I have a bunch of programs that are hanging after I tried to manipulate the filesystem, some of which I tried to close without success.
CPU load is close to 0%.
I would guess there is some kind of a deadlock.

### Include any warning/errors/backtraces from the system logs

I have no idea how to reproduce it, or how I can gather any logs or traces.
But considering that nothing happened for 15+ minutes, I don't expect any changed in upcoming hours, unless I do a hard-reboot.
I don't have any important tasks for the next 15 hours, maybe more, so I can just leave my PC in its current state for a while.

If there are any instructions for what I can do to debug it, or capture something, I will be happy to help.
Maybe I could connect Visual Studio debugger somehow, or create some memory dump? I don't have any tools or skills to work with kernel, though.

**Comment by d-uzlov** [comment]
Or, if there is no one available, who could help me gather logs, during the weekend, I guess it wouldn't be too hard to wait until Monday.

**Comment by lundman** [comment]
Yeah if it's hung (zfs-wise) you'd need to dump all the stacks, but that's quite a setup needed and probably isn't worth it for your time. I will replicate what you have done and see if I can trigger it myself. 
I think maybe there is a way to do a full memory.dmp and dump all the stacks, but I've not yet tried it. 
It most likely isn't too hard to trigger again, so let me have a go at it and go ahead and reboot.

**Comment by EchterAgo** [comment]
I believe I'm seeing the same stalls with `rclone` sometimes, I'll try to get stack dumps the next time it happens.

**Comment by lundman** [comment]
actually, you seem to know your way around VS. You can run, either from a BSOD (manually triggered) or just breaking into the debugger.

`.logopen c:\src\stacks.txt ; !stacks 2; .logclose`

it will dump all the stacks, and we can see whats hung.

**Comment by EchterAgo** [comment]
@d-uzlov it could be that this is fixed with 5c4290b3b7a5d0cbb325641b6e8ae422e3b276e3. This is not in a release yet, so you'll have to wait for the next one.

**Comment by lundman** [comment]
If you guys missed the irc announce, I pushed out rc5 for testing.

**Comment by EchterAgo** [comment]
RC5 looks like a great release candidate, I'll try to give it much testing, on my physical machine too. Maybe push the RC5 commit to a branch as well, I'm getting `This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.` when looking at the commit https://github.com/openzfsonwindows/openzfs/commit/51ee5642ed49a69a6bbd434a30c85d66391c568b

**Comment by lundman** [comment]
oops, i remember to push the tag, but not the branch itself. I should simplify the number of steps to codesign and make a release

**Comment by derritter88** [comment]
Same issue still occurs at the current `zfs-2.2.99-3-gf85bf35bc9` version.

`zpool export xxx` will result sometimes in an infinite process and all other `zpool` command will do nothing
