### ISSUE TITLE
Disabling block_cloning will leave files with all zeros.

### ISSUE THREAD

**Issue by guenther-alka** [openzfsonwindows/openzfs#485]
It is currently not possible to decide if older issues are still a problem, as they are still marked open even when solved. This is an item mainly for new users testing OpenZFS on Windows that has reached a quite usable state now.

As issues are listed by creation date, I suggest a separator between releases that can be very helpful.
This means that older issues that are still not solved should be reported again.

**Comment by lundman** [comment]
Yeah it isn't always possible to convince users to come back to try issues again. We will most likely just have to close-due-to-stale at some point, and have issue re-created, or at least updated, for each release.

Also, make a list of things for me to work on, so I don't just sit around doing nothing :)

**Comment by guenther-alka** [comment]
propably a special problem on my setup:
- if I deinstall openzfs completely and reinstall, openzvol is missing

prior doing nothing: 
- Windows Previous Versions=ZFS snaps is still on my wishlist

**Comment by testcb00** [comment]
I find that files become corrupted during the copy process in Windows 11.

Testing Equipment:
- Windows 10 PC
- Windows 11 PC
- Windows 11 VM on a Windows 10 PC
- NVMe SSD in an RTL9220 enclosure

Procedure:
1. Create a ZFS pool.
2. Copy a file from an NTFS drive to the mounted ZFS pool (file A -> file A1).
3. Use 7-Zip to compare checksums; they differ, A and A1 are same.
4. Copy and paste the file (file A1 -> file A2) again within the mounted ZFS pool.
5. Use 7-Zip to compare checksums; A/A1 and A2 differ, indicating the file (A2) is corrupted.
Observations:
- The Windows 10 PC does not exhibit this issue.
- Only the Windows 11 PC and VM are affected.

**Comment by lundman** [comment]
You need to check if it is corruption in bytes of the file, or, EAs differ, or metadata differ. I am unfamiliar with 7-Zip, but if it is just a pure-data checksum, it would suggest the first.

Did "3" meant to have "they don't differ" ?

**Comment by lundman** [comment]
```
$ md5sum.exe /c/src/tools/Pippin.jpg /e/Pippin*
7e9ace53cca208f3dc4f26edb29a6e32 */c/src/tools/Pippin.jpg
7e9ace53cca208f3dc4f26edb29a6e32 */e/Pippin - Copy - Copy - Copy - Copy - Copy.jpg
7e9ace53cca208f3dc4f26edb29a6e32 */e/Pippin - Copy - Copy - Copy - Copy.jpg
7e9ace53cca208f3dc4f26edb29a6e32 */e/Pippin - Copy - Copy - Copy.jpg
7e9ace53cca208f3dc4f26edb29a6e32 */e/Pippin - Copy - Copy.jpg
7e9ace53cca208f3dc4f26edb29a6e32 */e/Pippin - Copy.jpg
7e9ace53cca208f3dc4f26edb29a6e32 */e/Pippin.jpg
```

Not easy to replicate

**Comment by testcb00** [comment]
I can provide a video demonstrating the issue, possibly tomorrow. My test files include `.pdf`, `.xlsx`, and `.dwg` formats.  
I also tested a `.txt` file, which did not get corrupted.

Additionally, I tested saving to the local disk on Windows 11, and the issue persists. The corrupted files cannot be opened by Excel, a PDF reader, or AutoCAD.

**Comment by testcb00** [comment]
https://github.com/testcb00/uploaduse/blob/main/20250723-openzfsonwindows/W9KeOPXH3b.mp4
use 2.3.1rc10

**Comment by lundman** [comment]
Video not so useful. But if it can be replicated with .pdf file, you could do a TXT hexdump of the file before, and after corruption. Then we can see more clearly what changes.

**Comment by sskras** [comment]
The "Recycle Bin on D:\ is corrupted" message box reminds of this 1y old comment from Sep 2024:
https://github.com/openzfsonwindows/openzfs/discussions/396#discussion-7135780:~:text=recycle%20bin%20is%20corrupt

**Comment by lundman** [comment]
yeah I think we fixed that once, and now it is back after correcting the uid,gid work. I suspect the fix was wrong tho, and mostly luck it worked. It is annoying but harmless, so it is on TODO

**Comment by testcb00** [comment]
![Image](https://github.com/user-attachments/assets/a6207c95-36be-4b35-b628-38c8cf91449b)
[1 - Copy.txt](https://github.com/user-attachments/files/21393551/1.-.Copy.txt)
<img width="653" height="152" alt="Image" src="https://github.com/user-attachments/assets/a01cf489-c79b-4cc7-a46d-879060145778" />
[1.txt](https://github.com/user-attachments/files/21393550/1.txt)

<img width="2005" height="1623" alt="Image" src="https://github.com/user-attachments/assets/024ec41b-4bf4-4dd2-8aa3-05ba5baf00b0" />

It seems that the copy just creates a file of the same size, but no data is written to it, so the empty file's checksum is always the same since the number of bytes is identical (all zeros).

**Comment by lundman** [comment]
That is alarming, I assume trim is off, so we can ignore that.
Next I think FileSpy would be interesting, to see if we get calls to WRITE.

**Comment by testcb00** [comment]
Is FileSpy a native Windows application?

Besides, I tried MSYS2, and the cp function created an identical file (same as original file, not 00).

**Comment by lundman** [comment]
FileSpy.exe is from https://zezula.net/en/tools/filespy.html
You run as Administrator, then select the drive letter of the ZFS Volume. It does get verbose, so best is to Start, make the issue happen, then Stop - and try to make it as a small interval as possible. 

`cp` creates a valid file, so far, it happens only with copy/paste in Explorer?

**Comment by aspseka** [comment]
This reminds me of https://github.com/openzfsonwindows/openzfs/issues/497. The symptoms are quite similar, although I could not reproduce it reliably.

**Comment by testcb00** [comment]
[FileSpy.spy.txt](https://github.com/user-attachments/files/21417365/FileSpy.spy.txt)

Here is the FileSpy log. Please remove the fake .txt extension.

I'm not entirely sure, but in Windows 10, it seems to run fine—although high I/O operations may cause a BSOD. For example, using MSYS2 rsync to back up files to the ZFS drive while simultaneously opening a game save on the same ZFS drive can trigger a BSOD.

My goal is to use the drive for data storage, taking advantage of ZFS snapshots for versioning. I have a FreeBSD storage server, so I can zfs send snapshots to the server and recover datasets when necessary.

**Comment by lundman** [comment]
OK, I assume we are talking about "1 - Copy.png".

So roughly, what we have is
```

\Device\ZFS{6f4af52e-de57-38ee-83e1-04196826815c}\1 - Copy.png	STATUS_SUCCESS	FILE_CREATE CreOpts: 00000044 Access: 0017019F Share:  0 Attrib: 00000020 Result: FILE_CREATED

> Create file "1 - Copy.png"

\Device\ZFS{6f4af52e-de57-38ee-83e1-04196826815c}\1 - Copy.png	STATUS_SUCCESS	FSCTL_SET_SPARSE (000900C4)

> Make "1 - Copy.png" be sparse

\Device\ZFS{6f4af52e-de57-38ee-83e1-04196826815c}\1 - Copy.png	STATUS_SUCCESS	FileEndOfFileInformation EndOfFile: 00000000-000046A2

> Make "1 - Copy.png" be of size 0x46a2 (empty)

\Device\ZFS{6f4af52e-de57-38ee-83e1-04196826815c}\1 - Copy.png\:Zone.Identifier:$DATA	STATUS_SUCCESS	FILE_OVERWRITE_IF CreOpts: 00000004 Access: 00120117 Share:  00000007 Attrib: 0 Result: FILE_CREATED

> Create EA/xattr "Zone.Identifier" (in "1 - Copy.png" )


\Device\ZFS{6f4af52e-de57-38ee-83e1-04196826815c}\1 - Copy.png	STATUS_SUCCESS	FileBasicInformation CreateTime: 0 LastAccTime: 0 LastWrtTime: 01DBFC01-8337EC00 ChangeTime: 01DBFC01-86F3CF27 Attrib: 0

\Device\ZFS{6f4af52e-de57-38ee-83e1-04196826815c}:Zone.Identifier:$DATA:Zone.Identifier:$DATA	STATUS_SUCCESS	FileFsSizeInformation TotalClusters: E7F85 AvailClusters: E6D86 SectorsPerClus: 1 BytesPerSect: 1000

> Hm this is odd, should never have two "Zone.Identifier"



\Device\ZFS{6f4af52e-de57-38ee-83e1-04196826815c}:Zone.Identifier:$DATA:Zone.Identifier:$DATA	STATUS_SUCCESS	FileEndOfFileInformation EndOfFile: 00000000-0000001A

> Make "Zone.Identifier:Zone.Identifier" be size 0x1a

\Device\ZFS{6f4af52e-de57-38ee-83e1-04196826815c}:Zone.Identifier:$DATA:Zone.Identifier:$DATA	STATUS_SUCCESS	Offset: 00000000-00000000 ToWrite: 1A Written: 1A 

> Write 0x1a bytes to "Zone.Identifier:Zone.Identifier"

\Device\ZFS{6f4af52e-de57-38ee-83e1-04196826815c}:Zone.Identifier:$DATA:Zone.Identifier:$DATA	STATUS_SUCCESS	Offset: 00000000-00000000 ToRead: 10000 Read: 1A 

> Read in all 0x1a bytes from "Zone.Identifier:Zone.Identifier"

\Device\ZFS{6f4af52e-de57-38ee-83e1-04196826815c}:Zone.Identifier:$DATA:Zone.Identifier:$DATA	STATUS_SUCCESS	FileBasicInformation CreateTime: 0 LastAccTime: 0 LastWrtTime: 01DBFC01-8337EC00 ChangeTime: 01DBFC01-86F3CF27 Attrib: 0

```

Best guess here is that it queries the name for `"1 - Copy.png\:Zone.Identifier:$DATA"` at some point, and I return the full `"1 - Copy.png\:Zone.Identifier:$DATA"`, but perhaps I am expected to return the true file name `"1 - Copy.png"` only. Then it blindly concatenates `"Zone.Identifier:$DATA"` to the returned named, creating the double `"Zone.Identifier:$DATA:Zone.Identifier:$DATA"`. 

Unsure this is what goes wrong with this bug, but it is definitely wrong.


This is where we see the faulty double  `"Zone.Identifier:$DATA:Zone.Identifier:$DATA"` for the first time:


```
explorer.exe	IRP_MJ_QUERY_VOLUME_INFORMATION		\Device\ZFS{6f4af52e-de57-38ee-83e1-04196826815c}:Zone.Identifier:$DATA:Zone.Identifier:$DATA	STATUS_SUCCESS	FileFsAttributeInformation FileSysAttr: 19C502FF MaxNameLen: 255 FsName: NTFS
explorer.exe	IRP_MJ_QUERY_VOLUME_INFORMATION		\Device\ZFS{6f4af52e-de57-38ee-83e1-04196826815c}:Zone.Identifier:$DATA	STATUS_SUCCESS	FileFsSizeInformation TotalClusters: E7F85 AvailClusters: E6D86 SectorsPerClus: 1 BytesPerSect: 1000
explorer.exe	IRP_MJ_QUERY_VOLUME_INFORMATION		\Device\ZFS{6f4af52e-de57-38ee-83e1-04196826815c}:Zone.Identifier:$DATA:Zone.Identifier:$DATA	STATUS_SUCCESS	FileFsSizeInformation TotalClusters: E7F85 AvailClusters: E6D86 SectorsPerClus: 1 BytesPerSect: 1000
explorer.exe	IRP_MJ_SET_INFORMATION		\Device\ZFS{6f4af52e-de57-38ee-83e1-04196826815c}:Zone.Identifier:$DATA:Zone.Identifier:$DATA	STATUS_SUCCESS	FileEndOfFileInformation EndOfFile: 00000000-0000001A

```

**Comment by lundman** [comment]
OK so I have fixed the Zone.Identifier issue in https://github.com/openzfsonwindows/openzfs/releases/download/zfswin-2.3.1rc10/OpenZFSOnWindows-debug-2.3.1rc10v2.exe
it is unlikely to be the real cause, but it lets us exclude it in the debugging.

**Comment by testcb00** [comment]
[FileSpy_20250802.spy.txt](https://github.com/user-attachments/files/21560708/FileSpy_20250802.spy.txt)
FYI. Using OpenZFSOnWindows-debug-2.3.1rc10v2

**Comment by lundman** [comment]
Looks better, but it has this:
```
IRP_MJ_CREATE	\Device\ZFS{6f4af52e-de57-38ee-83e1-04196826815c}\1.png\:Zone.Identifier:$DATA
```

surely the `\:` is illegal? I wonder what NTFS does for that request.

**Comment by testcb00** [comment]
<img width="1466" height="361" alt="Image" src="https://github.com/user-attachments/assets/5a519493-1203-4c36-b33d-56edf9f040b8" />

Not sure.

I found another strange behaviour. I tried to export the pool and re-import it, but it stopped with return 0. Rebooted the VM, and the pool still exists in File Explorer (the export process seems to have failed).

I also tried downgrading to OpenZFSOnWindows-debug-2.3.1rc9, but no luck. It still stopped at "zunmount(zptest1,D:/) returns 0".

**Comment by lundman** [comment]
Looks like you clicked mouse in the window, push return?:)

**Comment by testcb00** [comment]
Same. Tried. Looks like zpool.exe has crashed. In Task Manager, the CPU and memory usage of zpool.exe remain unchanged.

**Comment by testcb00** [comment]
[FileSpy_20250803_1.spy.txt](https://github.com/user-attachments/files/21565449/FileSpy_20250803_1.spy.txt)

I create a new virtual disk (10GB), convert to GPT, create a new primary partition, create a new pool, assign letter to E:\, and then export it and re-import it. After that I copy the test image to the pool. Then start the test process.

Please see the result.

**Comment by lundman** [comment]
This sort of thing: https://youtu.be/n5KSADdAkTM ?

**Comment by testcb00** [comment]
Please see this
https://github.com/testcb00/uploaduse/blob/main/20250805-openzfsonwindows/firefox_pYKWwqhTug.mp4

**Comment by lundman** [comment]
No denying that goes wrong, the ::$DATA stream is all null, so it set sparse, but never filled in data. Question is why, and what is different about your Windows compared to mine (do others have this issue as well?) Do you have any software installed that doesn't come with Windows that is related?

**Comment by lundman** [comment]
Well now, I copied your process, including the create arguments:

`zpool.exe create -O casesensitivity=insensitive -o ashift=12 -O atime=off -O recordsize=256k -o feature@zilsaxattr=disabled -o feature@head_errlog=disabled -o feature@blake3=disabled -o feature@block_cloning=disabled -O compression=lz4 zptest2 PHYSICALDRIVE1
`
(Ok I used vhdx, no slow vhd for me!)

and sure enough, I get a all-zero copy.  Replicating should help me track it down, but I will start with which argument affects it.

**Comment by lundman** [comment]
OK  `-o feature@block_cloning=disabled`

Presumably I still advertise cloning (perhaps code doesn't check if it is disabled) and Windows tries to use it, and the basement of OpenZFS just rejects it.

**Comment by testcb00** [comment]
https://marek-g.github.io/posts/tips_and_tricks/zfs/zfs_on_windows/

I use this website to create a pool. At first, I thought creating a pool in Windows required different options than in FreeBSD, but now it seems I was wrong.

It looks like I can simply create a pool using the `zpool.exe create -O casesensitivity=insensitive -o ashift=12 -O atime=off -O compression=lz4 zptest2 PHYSICALDRIVE1` option instead of adding lots of settings.

**Comment by lundman** [comment]
We are pretty close to the same as FreeBSD so that sounds right.

**Comment by lundman** [comment]
OK rc10v3 should have a fix for this now.

**Comment by testcb00** [comment]
<img width="2547" height="1352" alt="Image" src="https://github.com/user-attachments/assets/dad0f643-7117-4fb1-b120-c3423ccf44c7" />

In rc10v3, I encountered another error. The VM OS is Windows 11 LTSC (24H2, build 26100.4652).

/dev/zfs and /proc/self/mounts are required.
Try running 'udevadm trigger' and 'mount -t proc proc /proc' as root.

**Comment by lundman** [comment]
That happens if driver is not loaded/installed

**Comment by testcb00** [comment]
Noted. I uninstalled rc10v3, rebooted, reinstalled it, and the copy function is now working. Thank you.

**Comment by lundman** [comment]
Awesome, thanks for reporting this issue.
