### ISSUE TITLE
0 Bytes files when cutting and pasting

### ISSUE THREAD

**Issue by Armin-windows** [openzfsonwindows/openzfs#524]
Unfortunately, the effect does not always occur!!!!

I'm experiencing a strange phenomenon when cutting and pasting.
I cut the aerofly folder in the test1 dataset and paste it into the test2 dataset. 
The folder has  4877 files. However, when moving, Windows shows that 5223 files are being moved, and suddenly there are 307 0-byte files in the destination dataset.
I can delete the 307 files.
The contents of the moved folder are also OK.

<img width="607" height="823" alt="Image" src="https://github.com/user-attachments/assets/b88aac43-77b0-4519-a86a-51680d855eb7" />

The contents of the folder look like this.

<img width="507" height="542" alt="Image" src="https://github.com/user-attachments/assets/64ca079c-f544-46e2-ae9b-ae2c4ad294ad" />

No additional files are created when copying, only when cutting and pasting.
When moving, it also says it has moved 5223 files, but no 0-byte files are created.
When copying, it also says it has moved 5223 files, although according to the properties there are only 4877 files in the folder and no 0-byte files are created.

**Comment by Armin-windows** [comment]
I just copied from a normal HDD Windows drive to the pool and got the same effect.


<img width="659" height="821" alt="Image" src="https://github.com/user-attachments/assets/2794ba0b-4c66-4756-ac95-7a0f8a2bf049" />

**Comment by lundman** [comment]
Ah ok, so it's not that it reads something wrong on source, but something happens when writing.

Most likely suspects could be that, let's say "1.HRM" is a Stream name in a file? Or, EA maybe. 

If you do just one file it doesn't happen? Smaller and smaller sets?

**Comment by Armin-windows** [comment]
I haven't seen this effect with individual files or small quantities of files.

**Comment by Armin-windows** [comment]
sorry, i found some files .

[cloudatlas.zip](https://github.com/user-attachments/files/22966429/cloudatlas.zip)

had to zip it up to upload it

**Comment by lundman** [comment]
Are those files means to make the 0-byte files when copy/paste?

**Comment by Armin-windows** [comment]
yes, always 0-byte files when copy/paste.

**Comment by lundman** [comment]
not happening here at all? Are some extra software installed that might be interjecting? virus scanners etc? Or can you run FileSpy on those, that will tell us what software does what

**Comment by Armin-windows** [comment]
https://github.com/user-attachments/assets/054ab1be-0381-49fd-a88a-b2b29105da27

**Comment by lundman** [comment]
Aha Zone.Identifier tells me it is creating EAs as files.  Good clue. The "paste with explorer" is some additional software, which one?

**Comment by lundman** [comment]
OK, do you need to cross into a reparsepoint (dataset mount) for it to happen?

**Comment by Armin-windows** [comment]
Paste with Explorer is not additional software. The selection window only appears because Teracopy is also installed and then offers a selection. Without Teracopy, it would immediately paste the file with Explorer.

It doesn't happen when I copy directly to the tank.
It only happens when copying to a dataset, e.g., Tank/test1.

**Comment by lundman** [comment]
OK so you need to cross into a reparse point, and possibly with Teracopy installed.  I will try that

**Comment by Armin-windows** [comment]
yes but teracopy is only a possibility ,i dont use it to copy these files.

**Comment by lundman** [comment]
Hmm I am unable to install TeraCopy on my VM due to BSOD (without ZFS on it), so I am not able to test that side of things. 

0x0_TeraCopy!dbkFCallWrapperAddr

**Comment by lundman** [comment]
ok let it BSOD, reboot, and it is running at least. 

But does not create the issue anyway. So there is something else maybe.

**Comment by lundman** [comment]
Hmm there seems to be a mounting issue with the new code, the lower datasets do not always get mounted correctly here.  I can see in you video that "test" has the right icon, but "test2" does not. 

If I issue "zfs unmount BOOM/dataset ; zfs mount BOOM/dataset" it is corrected, so there must be a race in the new code. Although, why would you be running new zpool/zfs

**Comment by Armin-windows** [comment]
gestern nach dem boot.

<img width="1140" height="286" alt="Image" src="https://github.com/user-attachments/assets/05f47ea2-aa94-4ee0-85e9-0d1b1b491b09" />

today after boot .

<img width="239" height="222" alt="Image" src="https://github.com/user-attachments/assets/f761fdff-0c00-4425-80d4-e89308fbf500" />

**Comment by Armin-windows** [comment]
after unmount and mount tank/snap tank/test tank/test2 it looks so.

<img width="223" height="170" alt="Image" src="https://github.com/user-attachments/assets/1d7e98f8-0ffd-4314-a739-107e069f9d74" />

but the 0-Byte Problem is still here

**Comment by lundman** [comment]
thanks for ruling that out.

**Comment by lundman** [comment]
Not having any luck triggering it here, could you do a FileSpy.exe exactly when you paste?  To tell FileSpy to monitor your lower dataset, use Volumes > "Attach to a device by name" > "E:\data" or whatever your path is.

**Comment by Armin-windows** [comment]
Sorry for the wait, I was away from home for a few days.
I tried filespy this morning, but it can't log mounted drives except for the recycle bin.
Here is an image after copying and deleting it to the Tank/test dataset.

<img width="993" height="524" alt="Image" src="https://github.com/user-attachments/assets/6579a662-64d4-46a4-89f3-42fa698d9ea6" />

In the video, you can see that the additional files are only created in datasets without drive letters.

https://github.com/user-attachments/assets/3706a921-72e1-4640-a0c3-ad834584d928

When I copy to the tank/test dataset, the two files are created there.
When I copy to a folder in the dataset, only the copied file is visible in this folder.
However, a second file is also created in Tank/test.

https://github.com/user-attachments/assets/45e43fd1-e4e6-4582-9884-834811c338bb

**Comment by lundman** [comment]
Ah hmm interesting looking FileSpy, not sure which one that is, try this one

https://zezula.net/en/tools/filespy.html

**Comment by Armin-windows** [comment]
thanks, this filespy works better.
i copied the file to tank/test .

<img width="739" height="214" alt="Image" src="https://github.com/user-attachments/assets/69d98936-be32-4cb7-a330-ccea2ee8ab9b" />

[FileSpy.zip](https://github.com/user-attachments/files/23147381/FileSpy.zip)

a little bit shorter

[FileSpy1.zip](https://github.com/user-attachments/files/23147586/FileSpy1.zip)

**Comment by lundman** [comment]
Awesome, so here it creates it:

```
113	09:40:23.145		explorer.exe	IRP_MJ_CLOSE	00000404	FFFF930D7FCFE088	\Device\ZFS{efe880b4-2c32-37b0-a8b0-3f584bbc59ff}\cloudatlas.ttx	STATUS_SUCCESS	
114	09:40:23.145	1	explorer.exe	IRP_MJ_CREATE	00000884	FFFF930D7FCFD408	\Device\ZFS{efe880b4-2c32-37b0-a8b0-3f584bbc59ff}\Zone.Identifier	STATUS_SUCCESS	FILE_OVERWRITE_IF CreOpts: 00000064 Access: 00120196 Share:  0 Attrib: 00000080 Result: FILE_CREATED
116	09:40:23.146		explorer.exe	IRP_MJ_WRITE	00060A00	FFFF930D7FCFD408	\Device\ZFS{efe880b4-2c32-37b0-a8b0-3f584bbc59ff}\Zone.Identifier	STATUS_SUCCESS	Offset: 00000000-00000000 ToWrite: 19 Written: 19 
```

hmm now as to why

**Comment by lundman** [comment]
https://github.com/openzfsonwindows/openzfs/commit/0151db58c259df694db688fccfaa6730e9df95b3

**Comment by Armin-windows** [comment]
I have now installed rc13 and the issue is resolved.

Thank you very much.
 I will continue testing.

By the way, is it possible to encrypt a tank as well?

**Comment by lundman** [comment]
Excellent, thanks.

encryption should work, if it doesn't, let me know
